CLASS LHC_ZTAX_DDL_I_VAT2_PROC_FIELD DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZTAX_DDL_I_VAT2_PROC_FIELD RESULT RESULT.

ENDCLASS.

CLASS LHC_ZTAX_DDL_I_VAT2_PROC_FIELD IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

ENDCLASS.